services:
  - type: web
    name: name-analysis-api
    env: python
    plan: free

    # ── install your Python deps first ────────────────────────────────
    buildCommand: pip install -r requirements.txt

    # ── then run your Flask app with Gunicorn ─────────────────────────
    startCommand: gunicorn name_analysis_api:app

    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: SMTP_PASSWORD
        value: ${SMTP_PASSWORD}
